export const SECOND_TO_MILLISECONDS = 1000;
export const MINUTE_TO_MILLISECONDS = 60 * SECOND_TO_MILLISECONDS;
export const HOUR_TO_MILLISECONDS = 60 * MINUTE_TO_MILLISECONDS;
export const DAY_TO_MILLISECONDS = 24 * HOUR_TO_MILLISECONDS;
export const WEEK_TO_MILLISECONDS = 7 * DAY_TO_MILLISECONDS;
